@startuml
left to right direction
abstract class Usuario {
  - nome String
  - rg String
  - cpf String
  - endereco String
  - email String
  - senha String

  + login()
  + logout()
}

class Cliente{
  - profissao String
  - rendimentos ArrayList<Contrato>

  + criarPedido()
  + modificarPedido()
  + consultarPedido()
  + cancelarPedido()
}

abstract class Agente {
  - tipoAgente String

  + avaliarPedido()
  + modificarPedido()
}
enum TipoAgente {
    Banco
    Empresa
}

class Banco {
   + criarContratoCredito()
}

class Empresa{
}

class Pedido {
  - dataCriacao Date
  - status String
  - cliente Cliente
  - automovel Automovel
  - contrato Contrato

  + analisarPedido()
  + confirmarContrato()
  + modificarPedido()
  + cancelarPedido()
}

class Contrato {
  - dataAssinatura Date
  - valor Double
  - tipoContrato String
  - cliente Cliente
  - automovel Automovel
  - contratoCredito Credito
  - TipoContrato

  + gerarContrato()
  + cancelarContrato()
}
Enum TipoContrato {
    Cliente
    Empresa
    Banco
}

class Credito {
  - valorCredito Double
  - taxaJuros Double
  - prazo Int
  - bancoQueConcedeu Banco

  + calcularParcelas()
}
enum Prazo {
    12
    24
    36
    48
}

class Automovel {
  - matricula String
  - ano Int
  - marca String
  - modelo String
  - placa String
'  - proprietario ClienteEmpresaBanco

  + disponibilidade()
}

Cliente -r-|> Usuario
Agente -l-|>  Usuario
Agente <|-- Banco
Agente <|-l- Empresa
Agente -- "TipoAgente" TipoAgente
Pedido o-u- Cliente
Pedido -- Automovel
Pedido o-- Contrato
Contrato -r- Cliente
Contrato o-- Automovel
Contrato o-- Credito
Contrato -l- "TipoContrato" TipoContrato
Credito -- Banco
Prazo "Prazo" -r- Credito
Automovel -- Cliente
Automovel o-r- Empresa
Automovel o-- Banco

@enduml
