@startuml
left to right direction
skinparam linetype ortho

node "User's Computer" as UC{
    [Aplicação Web] as ClientApp
}
node "Applicaton Server" as AS {
    package "Aplication" as APP{
        [Sistema de Gestão\nde Pedidos / Contratos] as SG
        [Sistema de Construção WEB] as SW
        [JPA] as JPA
    }

}
database "DataBase" as DB {
    [Tables] as TB
}

UC ---- AS :<<HTTP>>
AS ----- DB :<<ODBC>>

ClientApp <...> SW
SG <.r.> SW
SG <.l.> JPA
JPA ...> TB

@enduml