@startuml
left to right direction
skinparam linetype ortho
    package View {
    [Sistema de Construção WEB] as SC
    [Sistema de Gestão de\nPedidos Contratados] as SG
}
package Controller {
         [Controlador de\nRequisições] as CTR
}
package Model {
    [Classes]
    [JPA]
}
database "DataBase" as DB {
    [Tables] as TB
}

AppUser <..> View

View <.l.> Controller
Model <.u.> Controller

Classes <..> JPA
JPA <..> TB

@enduml