@startuml
left to right direction
skinparam linetype ortho

node "User's Computer" as UC{
    [Aplicação Web] as AppUser
}

node "Applicaton Server" as AS{
    package View {
        [Sistema de Construção WEB] as SC
        [Sistema de Gestão de\nPedidos Contratados] as SG
    }
    package Controller {
             [Controlador de\nRequisições] as CTR
    }
    package Model {
        [Classes]
        [JPA]
    }
}

database "DataBase" as DB {
    [Tables] as TB
}

DB --l-- AS :\t\t\t\t\t<ODBC>>
UC -- AS :<<HTTP>>

AppUser <..> View
SC <.l.> SG

Controller <.r.> View
Controller <.l.> Model

Classes <..> JPA
JPA <..> TB

@enduml